#!/bin/bash
osascript -e 'activate application "iTerm"'
osascript -e 'tell application "System Events" to keystroke "t" using command down'
osascript -e 'tell application "iTerm" to tell session -1 of current terminal to write text "python -m SimpleHTTPServer"'
